### ISSUE TITLE
Why did you removed jsdocs from the project?

### ISSUE THREAD

**Issue by candidodmv** [gregrickaby/nextjs-typescript-starter#82]
Hello!

Thank you for share this starter template, it's very useful, but I seen that you made a recent commit removing the Jsdoc from the sample, please, could you provide more details of reason of this action?

**Comment by gregrickaby** [comment]
Hey @candidodmv 👋🏻

[This comment](https://www.reddit.com/r/typescript/comments/r3srin/comment/hmcxgxb/?context=3 ) sums it up: 

> Yes JSDocs work great with TypeScript. **Don't use them to provide type information** about input/outputs though as that's redundant, but **they are perfect to explain a function's purpose** or behavior and any additional details needed about the arguments or return value. 
> 
> It is mostly used for editor integrations where it'll show up as a tooltip when the user attempts to use a function/property with the JSDoc. 
> 
> It shouldn't be used everywhere because **many places are so self explanatory that they don't need it**, but if something isn't obvious, that can definitely improve the developer experience to have in-line documentation.

After reviewing the codebase, I didn't feel like I needed JSDocs to provide additional explanations for what I though were "self explanatory functions", such as `Layout()`, `Home()`, and `App()`.

**Comment by candidodmv** [comment]
Got It! The explanatory make all the sense, but.

Once it's a starter template at some point in the future, JsDocs will be necessary(when we have something more then `Layout()`, `Home()`, and `App()`), so, doesn't make sense to keep it in the project, amiming support someone in the future that is using this template?

**Comment by gregrickaby** [comment]
@candidodmv I just added JSDoc support back to this project. JSDocs should auto-complete 👍🏻

By default, JSDoc warnings are opt-in only! 

If you want ESLint to flag items, remove these lines from [.eslintrc.js](https://github.com/gregrickaby/nextjs-typescript-starter/blob/main/.eslintrc.js#L26-L29)

```.js
    'jsdoc/require-param': 'off',
    'jsdoc/require-param-type': 'off',
    'jsdoc/require-param-description': 'off',
    'jsdoc/require-returns': 'off',
```
